In [1]:
import numpy as np
np.exp(2)

7.38905609893065

In [2]:
np.log(np.e)

1.0

In [3]:
np.sin(np.pi)

1.2246467991473532e-16

In [4]:
np.sqrt(3)

1.7320508075688772

In [5]:
a=np.array([2,3,5,7,8])

In [6]:
a[0]

2

In [7]:
a[1:3]

array([3, 5])

In [8]:
a[2:-1]

array([5, 7])

In [14]:
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [13]:
c=np.arange(1,3,0.2)
c

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [15]:
a.dtype

dtype('int64')

In [16]:
c.dtype

dtype('float64')

In [18]:
d=np.array([1,2,3],dtype=np.float64)
d

array([1., 2., 3.])

In [20]:
d.dtype

dtype('float64')

In [21]:
e=np.arange(5.)
e

array([0., 1., 2., 3., 4.])

In [22]:
e.dtype

dtype('float64')

In [26]:
#二次元の配列
a=np.array([[2,3,4],[5,6,7]],dtype=np.float64)
a

array([[2., 3., 4.],
       [5., 6., 7.]])

In [27]:
a[0,1]

3.0

In [28]:
a[:,1]

array([3., 6.])

In [29]:
a[1,:]

array([5., 6., 7.])

In [30]:
a[0,2:]

array([4.])

In [31]:
a[0,:2]

array([2., 3.])

In [34]:
v=np.array([2.,3.,4.])#一次元
a=np.array([[1.,2.],[3.,4.]])#二次元，　数学における次元の取り扱いと意味が異なるので注意

In [35]:
a = np.arange(15.).reshape(3,5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [36]:
a.shape

(3, 5)

In [38]:
a.ndim#配列の次元数

2

In [40]:
a.size#要素数

15

In [42]:
a=np.arange(16.)

In [43]:
c=a.reshape(4,-1)

In [44]:
c

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [45]:
c.ravel()#一次元配列に戻す

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [46]:
c.reshape(-1)#同じ効果

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [48]:
b=np.arange(4.)
b

array([0., 1., 2., 3.])

In [49]:
b.reshape(-1,1)

array([[0.],
       [1.],
       [2.],
       [3.]])

In [50]:
b[:, np.newaxis]

array([[0.],
       [1.],
       [2.],
       [3.]])

In [51]:
b[:,None]

array([[0.],
       [1.],
       [2.],
       [3.]])

In [52]:
b.reshape(1,-1)

array([[0., 1., 2., 3.]])

In [53]:
b[np.newaxis, :]

array([[0., 1., 2., 3.]])

In [54]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
b=np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [60]:
c =np.empty((2,5))
c

array([[1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8]])

In [62]:
d = np.linspace(0,1,10)
d

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [67]:
a=np.array([[0,1,2,],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [68]:
b=np.array([[6,7,8],[9,10,11]])
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
np.r_[a,b]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [70]:
np.c_[a,b]

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [72]:
c=np.arange(3)
c

array([0, 1, 2])

In [75]:
d=np.arange(3,6)
d

array([3, 4, 5])

In [76]:
np.r_[c,d]

array([0, 1, 2, 3, 4, 5])

In [77]:
np.c_[c,d]

array([[0, 3],
       [1, 4],
       [2, 5]])

In [78]:
np.r_[a,c]

ValueError: all the input arrays must have same number of dimensions

In [79]:
np.r_[a,c.reshape(1,-1)]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])