In [2]:
import numpy as np
np.random.rand()

0.8947437139672982

In [3]:
np.random.rand()

0.978127168248192

In [4]:
np.random.rand(3,2)

array([[0.79356262, 0.48915342],
       [0.25038682, 0.23469247],
       [0.64393441, 0.99510689]])

In [5]:
np.random.rand(5)

array([0.63345842, 0.85845475, 0.37154697, 0.18124021, 0.59866119])

In [13]:
np.random.randint(100)

77

In [11]:
np.random.randint(4)

3

In [15]:
np.random.randint(10,20)

17

In [16]:
np.random.randint(5,size=(3,3))

array([[0, 1, 3],
       [1, 0, 3],
       [4, 3, 1]])

In [21]:
def throw_dice(n):
    return np.random.randint(1,7,size=n).sum()

In [22]:
throw_dice(10)

38

In [28]:
np.random.seed(10)#seedを保持すると同じ結果が得られることが保証されている
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [29]:
np.random.seed(10)
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [35]:
#seedの固定
def throw_dice2(n,random_seed=10):
    np.random.seed(random_seed)
    return np.random.randint(1,7,size=n).sum()

In [36]:
throw_dice2(10)

34

In [37]:
throw_dice2(10)

34

In [38]:
throw_dice2(100)

328

In [39]:
throw_dice2(100)

328

In [5]:
import numpy as np

class Dice:
    def __init__self(self):
        np.random.seed(0)
        self.sum_ = 0
    
    def throw(self):
        self.sum_ += np.random.randint(1,7)
    
    def get_sum(self):
        return self.sum_

In [6]:
d1 = Dice()
for _ in range (10):
    d1.throw()

AttributeError: 'Dice' object has no attribute 'sum_'

In [9]:
rs = np.random.RandomState(10)
rs.rand()

0.771320643266746

In [10]:
rs.rand()

0.0207519493594015