In [4]:
import numpy as np
a = np.arange(5.,)
a

array([0., 1., 2., 3., 4.])

In [5]:
a.sum()

10.0

In [6]:
a.mean()

2.0

In [7]:
a.max()

4.0

In [8]:
a.min()

0.0

In [10]:
b = np.arange(9.).reshape(3,3)
b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [11]:
b.sum()

36.0

In [13]:
b.sum(axis=0)

array([ 9., 12., 15.])

In [14]:
b.sum(axis=1)

array([ 3., 12., 21.])

In [16]:
a=np.arange(3.,8.)
a

array([3., 4., 5., 6., 7.])

In [17]:
np.exp(a)

array([  20.08553692,   54.59815003,  148.4131591 ,  403.42879349,
       1096.63315843])

In [18]:
np.log(a)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015])

In [19]:
np.sqrt(a)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131])

In [21]:
b=np.arange(9.).reshape(3,3)
b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [22]:
np.exp(b)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [23]:
a

array([3., 4., 5., 6., 7.])

In [24]:
a**2

array([ 9., 16., 25., 36., 49.])

In [25]:
np.array([x**2 for x in a])

array([ 9., 16., 25., 36., 49.])

In [27]:
b = np.empty(a.shape[0])
for i , x in enumerate(a):
    b [i] = x**2
b

array([ 9., 16., 25., 36., 49.])

In [29]:
a = np.arange(12.).reshape(4,3)
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [36]:
b = np.arange(3.).reshape(1,3)
c = np.arange(4.).reshape(4,1)

In [37]:
b

array([[0., 1., 2.]])

In [38]:
c

array([[0.],
       [1.],
       [2.],
       [3.]])

In [33]:
a + b

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.],
       [ 9., 11., 13.]])

In [34]:
a * c

array([[ 0.,  0.,  0.],
       [ 3.,  4.,  5.],
       [12., 14., 16.],
       [27., 30., 33.]])

In [39]:
b - c

array([[ 0.,  1.,  2.],
       [-1.,  0.,  1.],
       [-2., -1.,  0.],
       [-3., -2., -1.]])